flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template,  request, Blueprint
from flaskblog.models import Post

main = Blueprint('main',__name__)


@main.route("/")
@main.route("/home")
def home():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
	return render_template('home.html', posts=posts)

@main.route("/about")
def about():
    return render_template('about.html',title = 'About')

flaskblog/posts/routes.py
from flask import render_template, url_for, redirect, flash, abort, request, Blueprint
from flaskblog import db
from flaskblog.models import Post
from flask_login import login_required, current_user
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/newpost', methods=['GET', 'POST'])
@login_required
def newpost():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title = form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash(f'Your post has been created. ', 'success')
		return redirect(url_for('main.home'))
	return render_template('newpost.html', title='New Post', form=form, legend = 'Create Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def updatepost(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash(f'Your Post has been Updated! ', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('newpost.html', title = post.title, form=form, legend = 'Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def deletepost(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash(f'Your Post has been Deleted! ', 'success')
	return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, redirect, flash, url_for, request, Blueprint
from flask_login import current_user, login_required, login_user, logout_user
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateForm, ResetPasswordForm, ResetRequestForm
from flaskblog.models import User, Post
from flaskblog.users.utils import send_reset_email, save_picture
from flaskblog import db, bcrypt

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username = form.username.data, email = form.email.data, password = hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Your account has been created! Login now.', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html',title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash(f'Login Unsuccessful!, Please Check Email and Passwrod', 'danger')
	return render_template('login.html',title='Login', form=form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))


@users.route("/account", methods=['GET','POST'])
@login_required
def account():
	form = UpdateForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your Account info is Updated successfully','success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static',filename = 'propic/'+ current_user.image_file)
	return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def userpost(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username = username).first_or_404()
	posts = Post.query.filter_by(author = user).order_by(Post.date_posted.desc())\
			.paginate(per_page=5, page=page)
	return render_template('userpost.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def resetrequest():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = ResetRequestForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instruction to reset your password to you mail id', 'info')
		return redirect(url_for('users.login'))
	return render_template('resetrequest.html', title = 'Reset Password', form = form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def resettoken(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired Token!', 'warning')
		return redirect(url_for('users.resetrequest'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash(f'Your password has been changed! Login now.', 'success')
		return redirect(url_for('users.login'))
	return render_template('resettoken.html', title = 'Reset Passwored', form = form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<div class="fluid-container ">
		<h1>About Page</h1>	
	</div>
	
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="fluid-container border">
	<img class="rounded-circle profilepic " src="{{ image_file }}" alt="profilepic">
	<h2 class="account-heading">{{ current_user.username }}</h2>
	<p class="text-secondary clearfix">{{ current_user.email }}</p>
	<hr>
	<form action="" method="post" enctype="multipart/form-data">
	    {{ form.hidden_tag() }}
	    <fieldset>
		<legend class="border-bottom mb-4">Account Info</legend>
		<div class="form-group">
		    {{form.username.label(class="form-control-label")}}
		    {% if form.username.errors %}
			{{form.username(class="form-control is-invalid", placeholder="Enter Your Username")}}
			<div class="invalid-feedback">
			    {% for error in form.username.errors %}
				<span> {{ error }} </span>
			    {% endfor %}
			</div>
		    {% else %}
			{{form.username(class="form-control ", placeholder="Enter Your Username")}}
		    {% endif %}
		</div>
		<div class="form-group">
		    {{form.email.label(class="form-control-label")}}
		    {% if form.email.errors %}
			{{form.email(class="form-control is-invalid", placeholder="Enter Your Email")}}
			<div class="invalid-feedback">
			    {% for error in form.email.errors %}
				<span> {{ error }} </span>
			    {% endfor %}
			</div>
		    {% else %}
			{{form.email(class="form-control ", placeholder="Enter Your Email")}}
		    {% endif %}
		</div>
		<div class="form-group">
			{{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span class="text-danger"> {{ error }} </span> <br>
                {% endfor %}
            {% endif %}
		</div>
	    </fieldset>
	    <div class="form-group">
		{{form.submit(class="btn btn-info")}}
	    </div>
	</form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        {% for post in posts.items %}
        <div class="fluid-container border rounded content">
                <img class="rounded-circle postpic clearfix" src="{{url_for('static', filename='propic/'+post.author.image_file)}}" alt="">
                <h2><a class="title" href="{{ url_for('posts.post', post_id = post.id) }}">{{post.title}}</a></h2>
                <p class="font-italic text-muted small"> <a href="{{ url_for('users.userpost', username=post.author.username) }}">By - {{post.author.username}} </a>on {{post.date_posted.strftime('%Y-%m-%d') }}</p>
                <hr>
                <p class="lead">{{post.content}}</p>
            </div>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4 " href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4 " href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}  
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{{ url_for('static',filename = 'bootstrap.css')}}">
	<link rel="stylesheet" href="{{ url_for('static',filename = 'main.css')}}">
	<link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet"> 

	{% if title %}
		<title>Blog | {{ title }}</title>
	{% else %}
		<title>Blog | Home</title>
	{% endif %}
</head>
<body>

	<nav class="navbar navbar-light bg-info fixed-top">
        <div class="container">
            <a href="{{url_for('main.home')}}" style="color:#ffffff; text-shadow: 1px 1px 2px black;" class="navbar-brand">Flask Blog</a>
            
             <ul class="nav">
                <li class="nav-item "><a class="nav-link" href="{{url_for('main.home')}}">Home</a></li>
                <li class="nav-item "><a class="nav-link" href="{{url_for('main.about')}}">About</a></li>				
				{% if current_user.is_authenticated %}
					<li class="nav-item "><a class="nav-link  " href="{{url_for('posts.newpost')}}">New Post</a></li>
					<li class="nav-item "><a class="nav-link  " href="{{url_for('users.account')}}">Account</a></li>
					<li class="nav-item "><a class="nav-link  " href="{{url_for('users.logout')}}">Logout</a></li>
				{% else %}
					<li class="nav-item "><a class="nav-link btn btn-sm btn-primary " href="{{url_for('users.login')}}">Login</a></li>
					<li class="nav-item "><a class="nav-link btn btn-success btn-sm " href="{{url_for('users.register')}}">Register</a></li>
				{% endif %}
            </ul>
        </div>
    </nav>
	<div style="height: 80px;"> </div>
	<div class="container">	
		<div class="row">
			<div class="col-md-9 col-sm-8 col-xs-12">
				{% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
						{% for category, message in messages %}
							<div class="alert alert-{{category}}">
								{{ message }}
							</div>
						{% endfor %}
					{% endif %}
				{% endwith %}
				{% block content %}{% endblock%}
			</div>
			
			<div class="col-md-3 col-sm-4 col-xs-12 sidebar">
				<div class="border rounded sidebar">
                    <ul class="list-group">
                        <h3 class="list-group-item bg-info text-white">Topics</h3>
                        <li class="list-group-item"><a href="#">Profile</a></li>
                        <li class="list-group-item"><a href="#">Settings</a></li>
                        <li class="list-group-item"><a href="#">Follows</a></li>
                        <li class="list-group-item"><a href="#">Followers</a></li>
                    </ul>
                </div>
			</div>	
	</div>


	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="fluid-container">
    <div class="formcontainer">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{form.email(class="form-control is-invalid", placeholder="Enter Your Email")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control ", placeholder="Enter Your Email")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{form.password(class="form-control is-invalid", placeholder="Enter Your Password")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.password(class="form-control ", placeholder="Enter Your Password")}}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-info")}}
                <small class="text-muted">
                    <a href="{{ url_for('users.resetrequest') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="" href="{{url_for('users.register')}}">Sign Up</a>
        </small>
    </div>
</div>
{% endblock content %}

flaskblog/templates/newpost.html
{% extends "layout.html" %} {% block content %}
<div class="fluid-container border">
    <div class="formcontainer">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{form.title.label(class="form-control-label")}} {% if form.title.errors %} {{form.title(class="form-control is-invalid",
                    placeholder="Enter Your Post Title")}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span> {{ error }} </span>
                        {% endfor %}
                    </div>
                    {% else %} {{form.title(class="form-control ", placeholder="Enter Your Post Title")}} {% endif %}
                </div>
                <div class="form-group">
                    {{form.content.label(class="form-control-label")}} {% if form.content.errors %} {{form.content(class="form-control is-invalid",
                    placeholder="Write your Post content")}}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                        <span> {{ error }} </span>
                        {% endfor %}
                    </div>
                    {% else %} {{form.content(class="form-control ", placeholder="Write your Post content")}} {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-info")}}
            </div>
        </form>
    </div>
</div>

{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="fluid-container border rounded content">
            <img class="rounded-circle postpic " src="{{url_for('static', filename='propic/'+post.author.image_file)}}" alt="">
            <h2 class="title" >{{post.title}}</h2>
            {% if post.author == current_user %}
            <div class="datetime"> 
                <a class="btn btn-secondary btn-sm " href="{{ url_for('posts.updatepost', post_id = post.id) }}">Update</a>    
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">Delete</button>    
            </div>
            {% endif %}
            <p class="font-italic text-muted small datetime"><a href="{{ url_for('users.userpost', username=post.author.username) }}">By - {{post.author.username}} </a>on {{post.date_posted.strftime('%Y-%m-%d') }}</p>
            <hr>
            <p class="lead ">{{post.content}}</p>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.deletepost', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="fluid-container">
        <div class="formcontainer">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend class="border-bottom mb-4">Register</legend>
                    <div class="form-group">
                        {{form.username.label(class="form-control-label")}}
                        {% if form.username.errors %}
                            {{form.username(class="form-control is-invalid", placeholder="Enter Your Username")}}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.username(class="form-control ", placeholder="Enter Your Username")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{form.email(class="form-control is-invalid", placeholder="Enter Your Email")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.email(class="form-control ", placeholder="Enter Your Email")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.password.label(class="form-control-label")}}
                        {% if form.password.errors %}
                            {{form.password(class="form-control is-invalid", placeholder="Enter Your Password")}}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.password(class="form-control ", placeholder="Enter Your Password")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.confirm_password.label(class="form-control-label")}}
                        {% if form.confirm_password.errors %}
                            {{form.confirm_password(class="form-control is-invalid", placeholder="confirm your password")}}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.confirm_password(class="form-control ", placeholder=" confirm your password")}}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{form.submit(class="btn btn-info")}}
                </div>
            </form>
        </div>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/resetrequest.html
{% extends "layout.html" %}
{% block content %}
<div class="fluid-container">
    <div class="formcontainer">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{form.email(class="form-control is-invalid", placeholder="Enter Your Email")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control ", placeholder="Enter Your Email")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-info")}}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

flaskblog/templates/resettoken.html
{% extends "layout.html" %}
{% block content %}
<div class="fluid-container">
    <div class="formcontainer">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{form.password(class="form-control is-invalid", placeholder="Confirm Your password")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.password(class="form-control ", placeholder="Confirm Your password")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.confirm_password.label(class="form-control-label")}}
                    {% if form.confirm_password.errors %}
                        {{form.confirm_password(class="form-control is-invalid", placeholder="Enter Your password")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.confirm_password(class="form-control ", placeholder="Enter Your password")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-info")}}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

flaskblog/templates/userpost.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mb-3">Post By {{ user.username }} - ({{ posts.total }})</h1>
        {% for post in posts.items %}
        <div class="fluid-container border rounded content">
                <img class="rounded-circle postpic clearfix" src="{{url_for('static', filename='propic/'+post.author.image_file)}}" alt="">
                <h2><a class="title" href="{{ url_for('posts.post', post_id = post.id) }}">{{post.title}}</a></h2>
                <p class="font-italic text-muted small"> <a href="{{ url_for('users.userpost', username=post.author.username) }}">By - {{post.author.username}} </a>on {{post.date_posted.strftime('%Y-%m-%d') }}</p>
                <hr>
                <p class="lead">{{post.content}}</p>
            </div>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4 " href="{{ url_for('users.userpost',username=user.usernmae, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4 " href="{{ url_for('users.userpost',username=user.username , page=page_num) }}">{{ page_num }}</a>
                {% endif %}  
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}